#pragma config(Motor, port2, rightMotor, tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor, port3, leftMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port4, intakeMotor, tmotorServoContinuousRotation, openLoop)
#pragma config(Motor, port5, armMotor, tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(90)

#include "Vex_Competition_Includes.c" //Main competition background code...do not modify!


//void pre_auton()
//{
//bStopTasksBetweenModes = true;
//}

task main()

{
StartTask(autonomous);
startMotor(leftMotor, 100);
startMotor(rightMotor, 100);
wait(1.5);
stopMotor(leftMotor);
stopMotor(rightMotor);

}
