#pragma config(Motor,  port2,           bottomLeftMotor, tmotorVex269, openLoop)
#pragma config(Motor,  port3,           topLeftMotor,  tmotorVex393, openLoop)
#pragma config(Motor,  port4,           bottomRightMotor, tmotorVex269, openLoop)
#pragma config(Motor,  port5,           topRightMotor, tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
		while(true)
		{
			//Driving motor control
			motor[bottomLeftMotor] = vexRT[Ch3] * .98;
			motor[bottomRightMotor] = vexRT[Ch2];

			//Arm control
			if(vexRT[Btn6U] == 1)
			{
				motor[topLeftMotor] = 40;
				motor[topRightMotor] = 40;
			}
			if(vexRT[Btn6D] == 1)
			{
				motor[topLeftMotor] = -40;
				motor[topRightMotor] = -40;
			}
			if(vexRT[Btn6D] == 0 && vexRT[Btn6U] == 0)
			{
				motor[bottomLeftMotor] = 0;
				motor[bottomRightMotor] = 0;
			}
		}
}
